services:
  # Trading backend service
  trading-backend:
    build:
      context: .
      dockerfile: scripts/Dockerfile.backend
    container_name: sep-trading-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SEP_CONFIG_PATH=/app/config
      - PYTHONPATH=/app
      - PORT=5000
    env_file:
      - ./config/.sep-config.env
    volumes:
      - ./config:/app/config:ro
      - ./pki/digitalocean-ca-certificate.crt:/app/certs/ca-certificate.crt:ro
      - sep-data:/app/data
      - sep-logs:/app/logs
      - ./bin:/app/bin:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sep-network

  # WebSocket service for real-time updates
  websocket-service:
    build:
      context: .
      dockerfile: scripts/Dockerfile.websocket
    container_name: sep-websocket
    restart: unless-stopped
    ports:
      - "8765:8765"
    environment:
      - WS_HOST=0.0.0.0
      - WS_PORT=8765
    env_file:
      - ./config/.sep-config.env
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s = socket.socket(); s.settimeout(5); s.connect(('localhost', 8765)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - sep-network

  # Frontend web application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sep-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_API_URL=https://mxbikes.xyz
      - REACT_APP_WS_URL=wss://mxbikes.xyz/ws
      - REACT_APP_ENVIRONMENT=production
    depends_on:
      trading-backend:
        condition: service_healthy
      websocket-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sep-network

volumes:
  sep-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume_nyc3_01/sep-data
  sep-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume_nyc3_01/sep-data/logs

networks:
  sep-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16