version: '3.8'

services:
  sep-dev:
    build: .
    image: sep_build_env:latest
    container_name: sep_dev_container
    working_dir: /workspace
    volumes:
      - .:/workspace
      - sep_dev_cache:/workspace/build
      - sep_dev_home:/root
    ports:
      - "8080:8080"
      - "5432:5432"
      - "2222:22"  # SSH for remote development
    environment:
      - DISPLAY=${DISPLAY:-:0}
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: tail -f /dev/null  # Keep container running
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  sep_dev_cache:
  sep_dev_home:
