name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Website
      run: |
        cd website
        npm install
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages
        
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./website/dist
