name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Website
      run: |
        cd website
        npm install
        npm run build
        
    - name: Deploy to gh-pages
      run: |
        cd website/dist
        git init
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Deploy website"
        git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/SepDynamics/sep-trader.git HEAD:gh-pages
