name: Deploy SEP Dynamics Website

on:
  push:
    branches: [ main, master ]
    paths:
      - 'website/**'
      - 'docs/**'
      - '.github/workflows/deploy-website.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'website/package-lock.json'
        
    - name: Install Dependencies
      run: |
        cd website
        npm ci
        
    - name: Build Website
      run: |
        cd website
        npm run build
        
    - name: Setup Custom Domain
      run: |
        echo "sepdynamics.com" > website/dist/CNAME
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/dist
        force_orphan: true
        
    - name: Notify Deployment
      if: success()
      run: |
        echo "✅ Website deployed successfully to sepdynamics.com"
        echo "📊 Quantum-inspired financial intelligence platform is live!"
