name: Deploy Website

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Website
      run: |
        cd website
        npm install
        npm run build
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/dist
        cname: sepdynamics.com
        force_orphan: true
