name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-11 libgtest-dev nlohmann-json3-dev
      - name: Build Test
        run: g++-11 -std=c++17 tests/unit/data_pipeline_test.cpp -lgtest -lgtest_main -lpthread -o unit_test
      - name: Run Tests
        run: ./unit_test
